[package]
name = "wfc"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[profile.release]
lto = true

[dependencies]
image = "0.20"
rand_xorshift = "0.1"
rand = "0.6"
hashbrown = "0.1"
coord_2d = "0.2"
grid_2d = "0.11"
direction = "0.17"
